Repository 2011-team-chatime/graceshopper, pull requests merged in 2021-01, with the labels that each got.

#11 FEAT: All products backend
  package.json
  script/seed.js
  server/api/index.js
  server/api/products.js
  server/db/models/index.js
  server/db/models/product.js
Labels: enhancement

#12 FEAT: all projects frontend
  client/components/AllProducts.js
  client/routes.js
  client/store/index.js
  client/store/products.js
Labels: enhancement

#13 BUG: fixed bug in all products
  client/components/AllProducts.js
  client/components/navbar.js
  package-lock.json
  public/index.html
  public/style.css
Labels: bug

#17 BUG: fixed price and description for Product model
  server/db/models/product.js
Labels: bug

#19 BUG: Seed data for product price
  .travis.yml
  script/seed.js
  server/db/models/product.spec.js
Labels: bug

#21 DEPLOY: travis: activate deployment
  .travis.yml
Labels: enhancement

#23 README: added instructions to seed data to Heroku
  README.md
Labels: documentation

#24 Single product FE
  client/components/SingleProduct.js
  package-lock.json
  package.json
  public/style.css
Labels: enhancement

#25 test for single product and fixed bug in single product api route
  client/components/SingleProduct.js
  server/api/products.js
  server/api/products.spec.js
Labels: bug, enhancement

#26 added user permissions, testing, models, and seeding
  script/seed.js
  server/api/users.js
  server/api/users.spec.js
  server/auth/index.js
  server/db/models/user.js
  server/db/models/user.spec.js
Labels: enhancement

#30 FEAT: created sequelize model, associations, and seed data for order
  script/seed.js
  server/db/models/index.js
  server/db/models/order.js
Labels: enhancement

#29 FEATURE: Cart component
  client/components/Cart.js
  client/components/SingleProduct.js
  client/routes.js
  server/api/users.spec.js
Labels: enhancement

#27 Bug: updated all users test
  server/api/users.spec.js
Labels: bug

#31 -made items model
  server/db/models/index.js
  server/db/models/item.js
Labels: enhancement

#34 BUG: travis import issue
  client/routes.js
  server/api/users.spec.js
Labels: bug

#39 FEAT: added navbar links
  client/components/Contact.js
  client/components/navbar.js
  client/routes.js
  public/style.css
Labels: enhancement

#37 Added functional cart component
  client/components/Cart.js
  client/components/SingleProduct.js
  client/store/cart.js
  script/seed.js
  server/api/orders.js
  server/db/models/index.js
  server/db/models/item.js
Labels: enhancement

#40 FEAT: filter all products
  client/components/AllProducts.js
Labels: enhancement

#43 FEAT: added 'Cart' to navbar and changed 'Home' to 'My Profile'
  client/components/navbar.js
Labels: enhancement

#45 FEAT: user can go to SingleProduct view from Cart by clicking product image
  client/components/Cart.js
Labels: enhancement

#46 Feature: add to cart and all product to single product link
  client/components/AllProducts.js
  client/components/SingleProduct.js
  client/store/cart.js
  server/api/orders.js
Labels: enhancement

#44 FEATURE: Delete From Cart Button Working For Logged In User
  client/components/AllProducts.js
  client/components/Cart.js
  client/components/Contact.js
  client/components/SingleProduct.js
  client/store/cart.js
  script/seed.js
  server/api/orders.js
  server/db/models/index.js
  server/db/models/item.js
Labels: enhancement

#42 FEAT: User profile displays name, email, address, and credit card info
  client/components/navbar.js
  client/components/user-home.js
  client/components/user-home.spec.js
Labels: enhancement

#47 BUG: fixed merge conflict in the cart redux file
  client/store/cart.js
Labels: bug

#49 CSS for all products, filter and single product
  client/components/AllProducts.js
  client/components/Cart.js
  client/components/SingleProduct.js
  public/style.css
  server/api/orders.js
  server/db/models/product.js
Labels: enhancement

#50 FEAT: A logged in user can checkout and will be redirected to order confirmation page
  client/components/Cart.js
  client/components/Checkout.js
  client/components/Confirmation.js
  client/routes.js
  client/store/cart.js
  server/api/orders.js
Labels: enhancement

#48 BUG: Fixed Delete Cart for Guest
  client/components/Cart.js
  client/store/cart.js
  server/api/orders.js
Labels: bug

#52 FEAT: Contact Us page renders with fake info
  client/components/Contact.js
Labels: bug, enhancement

#51 CartIcon and additional styling in AllProducts and SingleProduct
  client/components/AllProducts.js
  client/components/CartIcon.js
  client/components/navbar.js
  package-lock.json
  package.json
  public/style.css
  server/db/models/product.js
Labels: enhancement

#53 Bug: Fixed syntax error in cart component
  client/components/Cart.js
Labels: bug

#55 Updated checkout functions
  client/components/Checkout.js
  client/components/CheckoutPath.js
  client/components/Confirmation.js
  client/components/GuestCheckout.js
  client/routes.js
  client/store/user.js
  public/style.css
  server/api/orders.js
  server/api/users.js
Labels: enhancement

#62 BUG: cart total updates correctly.
  client/store/cart.js
  server/api/orders.js
  server/db/models/order.js
Labels: bug

#64 FEAT: Cart Quantity Updates For Logged In Users
  client/components/Cart.js
  client/components/SingleProduct.js
  client/store/cart.js
  public/style.css
  script/seed.js
  server/api/orders.js
  server/db/models/index.js
  server/db/models/order.js
Labels: enhancement

#65 FEAT: Guests are directed to the correct checkout page and guest orders persist in the database
  client/components/Cart.js
  client/components/Checkout.js
  client/components/GuestCheckout.js
  client/store/cart.js
  client/store/user.js
  server/api/orders.js
Labels: enhancement

#66 Added items to guest cart
  client/store/cart.js
  public/style.css
Labels: bug

#67 Guest can add a product to Cart
  client/components/AllProducts.js
  client/components/SingleProduct.js
  client/store/cart.js
Labels: enhancement

#68 Added remove quantity for guest
  client/store/cart.js
  script/seed.js
  server/api/orders.js
Labels: enhancement

#70 FEAT: Guest checkouts persist in database
  client/components/user-home.spec.js
  server/api/orders.js
Labels: enhancement

#71 redux to add product by admin
  client/components/AddProduct.js
  client/store/products.js
Labels: enhancement

#74 FEAT: Guests and new customers are directed to the correct checkout; guests can checkout
  client/components/Checkout.js
  client/components/CheckoutPath.js
  client/components/Confirmation.js
  client/components/NewCustomerCheckout.js
  client/routes.js
  client/store/cart.js
  server/api/orders.js
Labels: enhancement

#75 TEST: Added tests for api orders routes
  server/api/orders.spec.js
Labels: enhancement

#77 Fixed bug for checkout
  client/store/cart.js
  server/api/orders.js
  server/api/users.js
Labels: bug

#78 FEAT: Edit Product Form for admin only
  client/components/AddProduct.js
  client/components/AllProducts.js
  client/components/EditProduct.js
  client/components/ProductForm.js
  client/components/SingleProduct.js
  client/routes.js
  client/store/products.js
  public/style.css
Labels: enhancement

#80 BUG: Fixed Cart Item Order and Item Subtotal
  client/components/Cart.js
  package-lock.json
  package.json
Labels: bug

#82 Checkout unsigned user
  client/components/Checkout.js
  client/components/CheckoutPath.js
  client/components/NewCustomerCheckout.js
  client/store/cart.js
  client/store/user.js
  server/api/orders.js
Labels: enhancement

#84 Homestyling
  client/components/Cart.js
  client/components/HomePage.js
  client/components/navbar.js
  client/routes.js
  package-lock.json
  package.json
  public/index.html
  public/style.css
  script/seed.js
  server/db/models/product.js
Labels: enhancement

#83 FEAT: styling for single products and checkout pages
  client/components/AllProducts.js
  client/components/Checkout.js
  client/components/CheckoutPath.js
  client/components/Confirmation.js
  client/components/NewCustomerCheckout.js
  client/components/SingleProduct.js
  public/favicon.ico
  public/style.css
  script/seed.js
Labels: enhancement

#86 Added Css styling
  client/components/HomePage.js
  client/components/auth-form.js
  client/components/user-home.js
  package-lock.json
  package.json
  public/style.css
Labels: enhancement

#87 FEAT: Updated Design for All Products & Confirmation
  client/components/AllProducts.js
  client/components/Checkout.js
  client/components/Confirmation.js
  public/style.css
Labels: enhancement

#89 added pink buttons
  client/components/Cart.js
  client/components/Checkout.js
  client/components/CheckoutPath.js
  client/components/NewCustomerCheckout.js
  client/components/ProductForm.js
  client/components/SingleProduct.js
  client/components/auth-form.js
  client/components/user-home.js
Labels: enhancement
